### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Eun** [Eun/TFSMonkey#1]
- [ ] Allow custom credentials
- [x] Placeholder for Combobox
- [x] Show associated work items in the history
- [x] Work Items Icons
- [x] Refresh on F5 KeyPress 
- [x] Load TFS Urls From VS
- [ ] Set Workitem state via context menu
